person_one = input("What is the age of the first person? ")
person_two = input("What is the age of the second person? ")
person_one = int(person_one)
person_two = int(person_two)
print (abs(person_one - person_two))
